name: Commit

on: 
  push:
  pull_request: 
    branches: [master]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm run lint:js 
          npm run lint:css
          npm run build 
        