name: Push

on: 
  pull-request:
    branches: [master]


jobs:
  deploy:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Push
          run: |
            npm run build
            npm run deploy